version: "2"
services:
  peer1:
    image: recp/discovery-eureka:0.0.1-SNAPSHOT
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    ports:
      - "18761:18761"
    environment:
      - spring.profiles.active=peer1
  peer2:
    image: recp/discovery-eureka:0.0.1-SNAPSHOT
    networks:
      app_net:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::10
    ports:
      - "18762:18762"
    environment:
      - spring.profiles.active=peer2
  service-tp-zuti:
    image: recp/service-tp-zuti:0.0.1-SNAPSHOT
    depends_on:
        -  config-server
    networks:
      app_net:
        ipv4_address: 172.16.238.12
        ipv6_address: 2001:3984:3989::10
  config-server:
    image: recp/config-server:0.0.1-SNAPSHOT
    depends_on:
        -  gateway-zuul
    networks:
      app_net:
        ipv4_address: 172.16.238.13
        ipv6_address: 2001:3984:3989::10
  gateway-zuul:
    image: recp/gateway-zuul:0.0.1-SNAPSHOT
    depends_on:
        -  peer2
        -  peer1
    networks:
      app_net:
        ipv4_address: 172.16.238.14
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1 
